name: GitHub Actions Build and Deploy Storybook
on: 
  push:
    branches:
      - 'dev' # Trigger the action only pushed to a specific branch
      - '!main' # Ignore if pushed to a specific branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
      - name: Use Node js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Merge dev -> storybook-deploy ðŸš€
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: dev
          target_branch: storybook-deploy
          github_token: ${{ github.token }}